import {
  SiC,
  SiCplusplus,
  SiCsharp,
  SiPython,
  SiJavascript,
  SiTypescript,
  SiKotlin,
  SiPhp,
  SiGo,
  SiRust,
  SiRuby,
  SiSwift,
  SiDart,
  SiSqlite,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiFirebase,
  SiAmazonaws,
  SiGooglecloud,
  SiMicrosoftazure,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiBootstrap,
  SiStyledcomponents,
  SiSass,
  SiRedux,
  SiGit,
  SiGithub,
  SiDocker,
  SiKubernetes,
  SiVite,
  SiWebpack,
  SiBabel,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";


export const techIcons = {
  C: <SiC className="text-sky-400 text-5xl" />,
  Cpp: <SiCplusplus className="text-blue-400 text-5xl" />,
  Csharp: <SiCsharp className="text-indigo-400 text-5xl" />,
  Python: <SiPython className="text-yellow-400 text-5xl" />,
  JavaScript: <SiJavascript className="text-yellow-300 text-5xl" />,
  TypeScript: <SiTypescript className="text-blue-400 text-5xl" />,
  Java: <FaJava className="text-red-500 text-5xl" />,
  Kotlin: <SiKotlin className="text-purple-400 text-5xl" />,
  PHP: <SiPhp className="text-indigo-300 text-5xl" />,
  Go: <SiGo className="text-cyan-400 text-5xl" />,
  Rust: <SiRust className="text-orange-700 text-5xl" />,
  Ruby: <SiRuby className="text-red-600 text-5xl" />,
  Swift: <SiSwift className="text-orange-500 text-5xl" />,
  Dart: <SiDart className="text-blue-500 text-5xl" />,

  // Frontend
  HTML: <SiHtml5 className="text-orange-500 text-5xl" />,
  CSS: <SiCss3 className="text-blue-500 text-5xl" />,
  React: <SiReact className="text-cyan-400 text-5xl" />,
  Next: <SiNextdotjs className="text-white text-5xl" />,
  Tailwind: <SiTailwindcss className="text-cyan-300 text-5xl" />,
  Bootstrap: <SiBootstrap className="text-purple-500 text-5xl" />,
  Sass: <SiSass className="text-pink-400 text-5xl" />,
  StyledComponents: <SiStyledcomponents className="text-pink-300 text-5xl" />,
  Redux: <SiRedux className="text-purple-400 text-5xl" />,

  // Backend
  NodeJS: <SiNodedotjs className="text-green-500 text-5xl" />,
  Express: <SiExpress className="text-gray-200 text-5xl" />,

  // Databases
  MongoDB: <SiMongodb className="text-green-500 text-5xl" />,
  MySQL: <SiMysql className="text-blue-500 text-5xl" />,
  PostgreSQL: <SiPostgresql className="text-blue-400 text-5xl" />,
  SQLite: <SiSqlite className="text-blue-300 text-5xl" />,
  Firebase: <SiFirebase className="text-yellow-400 text-5xl" />,

  // Cloud
  AWS: <SiAmazonaws className="text-orange-400 text-5xl" />,
  GCP: <SiGooglecloud className="text-blue-400 text-5xl" />,
  Azure: <SiMicrosoftazure className="text-blue-500 text-5xl" />,

  // Tools & DevOps
  Git: <SiGit className="text-orange-500 text-5xl" />,
  GitHub: <SiGithub className="text-white text-5xl" />,
  Docker: <SiDocker className="text-blue-400 text-5xl" />,
  Kubernetes: <SiKubernetes className="text-blue-500 text-5xl" />,
  Vite: <SiVite className="text-purple-400 text-5xl" />,
  Webpack: <SiWebpack className="text-blue-400 text-5xl" />,
  Babel: <SiBabel className="text-yellow-400 text-5xl" />,
};